SRC=..
include $(SRC)/Makefile.env

# change this to your library name
LIB_NAME = libamq

INCL	 = $(RTLIBINCL) $(TNMSG_INCL) -I./ -I./include \
        -I$(ACTIVEMQ)/include/activemq-cpp-3.1.3

# list object files 
OBJS =   ContentTable.o 	\
	 Message.o		\
	 QWMessageParser.o	\
	 QWMessageSerializer.o	\
	 AMQConnectionHandler.o	\
	 Connection.o		\
	 amqPropertiesST.o



#idl: ./IDL/QWPullSubServices.idl ./IDL/QWPushSubServices.idl ./IDL/QWSubscription.idl ./IDL/QWFeeder.idl
#	tao_idl -cs C.cc -ss S.cc -sT S_T.cc  -I./IDL IDL/QWPullSubServices.idl
#	tao_idl -cs C.cc -ss S.cc -sT S_T.cc  -I./IDL IDL/QWPushSubServices.idl
#	tao_idl -cs C.cc -ss S.cc -sT S_T.cc  -Wb,pre_include=headers.h -I./IDL IDL/QWSubscription.idl
#	tao_idl -cs C.cc -ss S.cc -sT S_T.cc  -I./IDL IDL/QWFeeder.idl


$(LIB_NAME): $(OBJS) 
	$(CC) -xar -o $@.a $(OBJS) $(FLAGS)
	$(CC) -G -o $@.so $(OBJS) $(FLAGS)

.C.o: 
	$(CC) $(USE_KPIC) $< -c $(CFLAGS) $(INCL) 

.cc.o: 
	$(CC) $(USE_KPIC) $< -c $(CFLAGS)  $(INCL) 


#conntest:
#	$(CC) -o $@ $@.cc $(OBJS) $(FLAGS) $(CORBA_FLAGS) $(INCL) $(LIBS) $(CORBA_LIBS) -L/usr/local/lib -lxerces-c -lc -lgen

clean:
#	-rm QWFeeder* QWSubscription* QWPull* QWPush*
	-rm -f *.o *.so *.a *~ core ${BIN} 
	-rm -fr SunWS_cache


veryclean:  clean
	makedepend
	-rm -f Makefile.bak

depend:
	makedepend $(CFLAGS) $(RTLIBINCL) $(CPPINC) *.c *.C

printvars:
	@echo DEVROOT=$(DEVROOT)
	@echo BIN=$(BIN)
	@echo CC=$(CC)
	@echo CFLAGS=$(CFLAGS)
	@echo CPPINC=$(CPPINC)
	@echo INCL=$(INCL)
	@echo BINOBJS=$(BINOBJS)
	@echo RTLIBINCL=$(RTLIBINCL)

# DO NOT DELETE
